---
abstract: 'RESTful web application framework based on Plack'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  HTTP::Request::Common: 0
  Plack::Test: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Leyland
recommends:
  JSON: 2.50
  JSON::XS: 2.3
requires:
  Carp: 0
  Data::Dumper: 0
  Devel::Declare::Interface: 0
  Devel::Declare::Parser: 0
  Encode: 0
  Exporter::Declare::Magic: 0.107
  JSON: 0
  Locale::Wolowitz: 0
  Module::Load: 0
  Moo: 0
  Moo::Role: 0
  Plack::Component: 0
  Plack::Request: 0
  Scalar::Util: 0
  Tenjin: 0.070001
  Text::SpanningTable: 0
  Throwable: 0
  Tie::IxHash: 0
  Try::Tiny: 0
  XML::TreePP: 0
  base: 0
  namespace::clean: 0
  parent: 0
  perl: 5.006
  strict: 0
  version: 0.77
  warnings: 0
resources:
  homepage: https://github.com/ido50/Leyland
  repository: https://github.com/ido50/Leyland.git
version: 1.000001
